"""empty message

Revision ID: 22cb12ae1140
Revises: 6431fb45929f
Create Date: 2020-04-10 11:35:00.434018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cb12ae1140'
down_revision = '6431fb45929f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('study', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.drop_constraint('study_teacher.id_fkey', 'study', type_='foreignkey')
    op.create_foreign_key(None, 'study', 'teacher', ['teacher_id'], ['id'])
    op.drop_column('study', 'teacher.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('teacher.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.create_foreign_key('study_teacher.id_fkey', 'study', 'teacher', ['teacher.id'], ['id'])
    op.drop_column('study', 'teacher_id')
    op.drop_column('study', 'id')
    # ### end Alembic commands ###
