"""empty message

Revision ID: 6431fb45929f
Revises: 
Create Date: 2020-04-10 07:46:50.372981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6431fb45929f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('index_student_key', table_name='student')
    op.add_column('study', sa.Column('teacher.id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'study', 'teacher', ['teacher.id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'teacher.id')
    op.create_index('index_student_key', 'student', ['name'], unique=False)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='persons_pkey')
    )
    # ### end Alembic commands ###
